### PR TITLE
MW-245: Move Coins filtering to Coins panel so that it can be used in Withdraw, Send and Backup tx page

### PR DESCRIPTION
**Pull request by alexyjs**
- https://github.com/layer2tech/mercury-wallet/issues/245

### CODE REVIEW

**Review by 86667 — CHANGES_REQUESTED** [review]
Thanks!

Only thing is If there are no coins the 3 dots do not fit the panel nicely.

**Comment by alexyjs** [comment]
Updated. Only show the filter if coin exists.

**Comment by 86667** [comment]
@alexyjs That doesnt work because a user may have 2 coins available but non IN_TRANSFER, if they then filter by IN_TRANSFER they cannot change back to default. 

Have the 3 dots always visible, just add some padding so that the panel is large enough for it.

**Review by 86667 — APPROVED** [review]
Good to go. Awaitign release of 0.2.14 so this can be included in 0.2.15

**Pull request merged**
