### PR TITLE
Withdraw, Send & Receive Lightning

### PR DESCRIPTION
**Pull request by DhananjayPurohit**
Issue #1798

### CODE REVIEW

**Comment by DhananjayPurohit** [comment]
Issue #1800

**Comment by DhananjayPurohit** [comment]
Issue #1805

**Comment by DhananjayPurohit** [comment]
Issue #1799

**Comment by DhananjayPurohit** [comment]
Includes all withdraw lightning issues

**Review by sgershuny — APPROVED** [review]

**Comment by DhananjayPurohit** [comment]
Issue #1809 & #1810

**Pull request merged**
