### PR TITLE
Received tx verification

### PR DESCRIPTION
**Pull request by tomt1664**
Verification of backup transaction received from the sender. 
This must be done explicitly as tx cannot be broadcast until the locktime expires. 

Checks:
Amounts
Destination address
inputs
signature validity
coin (input) unspent and correct value/txid. 

Also a fix to ensure deposit_confirm only called once.

### CODE REVIEW

**Comment by lawlawlaw** [comment]
The following tests fail:
  ● Statecoins/Coin › calcExpiryDate › Calculate expiry

  ● StateChain Entity › TransferReceiver › Incorrect decryption key

  ● StateChain Entity › TransferReceiver › Invalid StateChainSig

  ● StateChain Entity › TransferReceiver › Expect complete

**Comment by lawlawlaw** [comment]
Some tests are failing:
 ● Wallet › toJSON

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'ElectrumClient'
        |     property 'client' -> object with constructor 'WebSocketClient'
        --- property 'self' closes the circle
        at JSON.stringify (<anonymous>)

      17 |   test('toJSON', function() {
      18 |     wallet.config.update({min_anon_set: 1000}); // update config to ensure defaults are not revered to after fromJSON.
    > 19 |     let json_wallet = JSON.parse(JSON.stringify(wallet));
         |                                       ^
      20 |     let from_json = Wallet.fromJSON(json_wallet, bitcoin.networks.bitcoin, segwitAddr, true);
      21 |     // check wallets serialize to same values (since deep equal on recursive objects is messy)
      22 |     expect(JSON.stringify(from_json)).toEqual(JSON.stringify(wallet));

      at Object.<anonymous> (src/wallet/test/wallet.test.js:19:39)

  ● Wallet › save/load

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'ElectrumClient'
        |     property 'client' -> object with constructor 'WebSocketClient'
        --- property 'self' closes the circle
        at JSON.stringify (<anonymous>)

      26 |     wallet.save()
      27 |     let loaded_wallet = await Wallet.load('mock', '', true)
    > 28 |     expect(JSON.stringify(wallet)).toEqual(JSON.stringify(loaded_wallet))
         |                 ^
      29 |   });
      30 |
      31 |   test('save coins list', async function() {

      at Object.<anonymous> (src/wallet/test/wallet.test.js:28:17)

  ● Wallet › save coins list

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'ElectrumClient'
        |     property 'client' -> object with constructor 'WebSocketClient'
        --- property 'self' closes the circle
        at JSON.stringify (<anonymous>)

      40 |     let num_coins_after = loaded_wallet.statecoins.coins.length;
      41 |     expect(num_coins_after).toEqual(num_coins_before+1)
    > 42 |     expect(JSON.stringify(wallet)).toEqual(JSON.stringify(loaded_wallet))
         |                 ^
      43 |   });
      44 |
      45 |   test('genBtcAddress', function() {

      at Object.<anonymous> (src/wallet/test/wallet.test.js:42:17)

**Review by lawlawlaw — CHANGES_REQUESTED** [review]
Some wallet tests are failing - please correct before merging.

**Comment by tomt1664** [comment]
The tests pass when `testing_mode=true` (`testing_mode=false` for build).

**Pull request merged**
